name: Build and ush Docker Images

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [productcatalogservice, adservice, cartservice, checkoutservice, currencyservice, emailservice,frontend, loadgenerator,paymentservice, recommendationservice, shippingservice]

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}"|docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      
      - name: Build docker image for ${{matrix.service}}
        run: docker build -t ${{ secrets.DOCKER_USERNAME}} /${{matrix.service}}:${{github.sha}} -f ./${{matrix.service}}/ Dockerfile ./${{matrix.service}}
      
      - name:  Tag Docker imge with commit SHA and latest
        run: docker tag ${{ secrets.DOCKER_USERNAME}} /${{matrix.service}}:${{github.sha}} ${{ secrets.DOCKER_USERNAME}}/${{matrix.service}}:latest

      - name:  Push Docker image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}${{matrix.service}}:${{github.sha}}
             docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.service}}:latest
        
